# Generated by Django 2.0.2 on 2018-03-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
