# Generated by Django 2.0.2 on 2018-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20180318_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
