# Generated by Django 2.0.2 on 2018-03-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_booklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='song',
            new_name='book',
        ),
    ]
